-- module Stack (Stack, newS, freeCellsS, stackS, netS, holdsS, popS) where
--     data Stack = Sta[Palet] int deriving (Eq, Show)
--     newS :: int -> Stack
--     freeCellsS :: Stack -> int
--     stackS :: Stack -> Palet -> Stack
--     netS :: Stack -> int
--     holdsS :: Stack -> Palet -> Route -> bool
--     popS :: Stack -> string -> Stack

-- module Truck (Truck, newT, freeCellsT, loadT, unloadT, netT) where
--     data Truck = Tru[Stack] Route  -> Truck
--     freeCellsT :: Truck -> int
--     loadT :: Truck -> Palet -> Truck
--     unloadT :: Truck -> string -> Truck
--     netT :: Truck -> int